-- Invite codes for the closed beta (June 26) — see Docs/BLITZ_PLAN.md.
--
-- Design:
--   * invite_codes: per-channel batches (waitlist / discord / creator / ...),
--     max_uses + use_count, optional expiry. Generated by
--     scripts/generate-invite-codes.mjs which emits data-insert SQL.
--   * invite_redemptions: one row per redemption, one redemption per user.
--   * app_settings.require_invite_code: server-side kill switch. While
--     false (default), signup behaves exactly as today. Flip to true on
--     beta-open morning — no deploy needed:
--       UPDATE app_settings SET value = 'true' WHERE key = 'require_invite_code';
--   * Enforcement is an AFTER INSERT trigger on auth.users: when the flag is
--     on, signups must carry a valid code in raw_user_meta_data.invite_code
--     (the client sends it via signUp options.data). The trigger atomically
--     locks the code row, checks expiry/uses, increments, and records the
--     redemption — racing signups on the last use of a code serialize on the
--     row lock. A failed check raises, which rolls back the auth.users row;
--     Supabase surfaces it to the client as a generic signup error, so the
--     form pre-validates via validate_invite_code() for real UX.
--
-- Rollback: database/rollbacks/rollback_add_invite_codes.sql

-- ============================================================
-- 1. app_settings (generic runtime flags, public-read)
-- ============================================================

CREATE TABLE IF NOT EXISTS app_settings (
  key text PRIMARY KEY,
  value jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read app settings" ON app_settings;
CREATE POLICY "Anyone can read app settings"
  ON app_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins manage app settings" ON app_settings;
CREATE POLICY "Admins manage app settings"
  ON app_settings FOR ALL TO authenticated
  USING (is_admin_user())
  WITH CHECK (is_admin_user());

INSERT INTO app_settings (key, value)
VALUES ('require_invite_code', 'false'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- ============================================================
-- 2. invite_codes + invite_redemptions (admin-read; all writes
--    go through SECURITY DEFINER paths)
-- ============================================================

CREATE TABLE IF NOT EXISTS invite_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  channel text NOT NULL,
  note text,
  max_uses integer NOT NULL DEFAULT 1 CHECK (max_uses >= 1),
  use_count integer NOT NULL DEFAULT 0 CHECK (use_count >= 0),
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_invite_codes_channel ON invite_codes (channel);

CREATE TABLE IF NOT EXISTS invite_redemptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invite_code_id uuid NOT NULL REFERENCES invite_codes(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  redeemed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_invite_redemptions_code ON invite_redemptions (invite_code_id);

ALTER TABLE invite_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE invite_redemptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage invite codes" ON invite_codes;
CREATE POLICY "Admins manage invite codes"
  ON invite_codes FOR ALL TO authenticated
  USING (is_admin_user())
  WITH CHECK (is_admin_user());

DROP POLICY IF EXISTS "Admins read redemptions" ON invite_redemptions;
CREATE POLICY "Admins read redemptions"
  ON invite_redemptions FOR SELECT TO authenticated
  USING (is_admin_user());

-- ============================================================
-- 3. validate_invite_code — anon-callable pre-signup check.
--    Returns {valid, reason} without leaking channel/uses.
--    Codes are 31^8 (~850B) so enumeration is impractical.
-- ============================================================

CREATE OR REPLACE FUNCTION validate_invite_code(p_code text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  norm text;
  v invite_codes%ROWTYPE;
BEGIN
  norm := upper(regexp_replace(coalesce(p_code, ''), '\s', '', 'g'));
  IF norm = '' THEN
    RETURN jsonb_build_object('valid', false, 'reason', 'missing');
  END IF;

  SELECT * INTO v FROM invite_codes WHERE code = norm;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('valid', false, 'reason', 'not_found');
  END IF;
  IF v.expires_at IS NOT NULL AND v.expires_at < now() THEN
    RETURN jsonb_build_object('valid', false, 'reason', 'expired');
  END IF;
  IF v.use_count >= v.max_uses THEN
    RETURN jsonb_build_object('valid', false, 'reason', 'exhausted');
  END IF;

  RETURN jsonb_build_object('valid', true, 'reason', NULL);
END;
$$;

REVOKE ALL ON FUNCTION validate_invite_code(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION validate_invite_code(text) TO anon, authenticated;

-- ============================================================
-- 4. Signup enforcement trigger on auth.users
-- ============================================================

CREATE OR REPLACE FUNCTION enforce_invite_code_on_signup()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  required boolean;
  norm text;
  v invite_codes%ROWTYPE;
BEGIN
  SELECT value::boolean INTO required
  FROM app_settings WHERE key = 'require_invite_code';

  IF NOT COALESCE(required, false) THEN
    RETURN NEW;
  END IF;

  norm := upper(regexp_replace(coalesce(NEW.raw_user_meta_data->>'invite_code', ''), '\s', '', 'g'));
  IF norm = '' THEN
    RAISE EXCEPTION 'invite code required';
  END IF;

  -- Lock the code row so concurrent signups on the last use serialize.
  SELECT * INTO v FROM invite_codes WHERE code = norm FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'invalid invite code';
  END IF;
  IF v.expires_at IS NOT NULL AND v.expires_at < now() THEN
    RAISE EXCEPTION 'invite code expired';
  END IF;
  IF v.use_count >= v.max_uses THEN
    RAISE EXCEPTION 'invite code exhausted';
  END IF;

  UPDATE invite_codes SET use_count = use_count + 1 WHERE id = v.id;
  INSERT INTO invite_redemptions (invite_code_id, user_id) VALUES (v.id, NEW.id);

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION enforce_invite_code_on_signup() FROM PUBLIC;

DROP TRIGGER IF EXISTS trg_enforce_invite_code ON auth.users;
CREATE TRIGGER trg_enforce_invite_code
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION enforce_invite_code_on_signup();
